accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    #path(r'^$', views.index, name='index'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('register/', views.register, name='register'),
    path('ajax/', views.ajax, name='register'),
    #path(r'^profile/$', views.profile, name='profile'),
    #path(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
]

articles/urls.py
from django.urls import path
from . import views

# namespace the app to articles
app_name = 'articles'

urlpatterns = [
    path('',views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<slug:article_slug>/edit/', views.edit, name='edit'),
    path('<slug:article_slug>/delete/', views.delete, name='delete'),
    path('<slug:article_slug>/', views.get, name='get')
]

bloggy/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from bloggy import settings, views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('', views.home, name='home'),
    path('captcha/', include('captcha.urls')),
    re_path('favicon\.ico$', favicon_view),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(default= 'default.png', blank=True)
    author = models.ForeignKey(User,default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']

    def snippet(self):
        return self.body[:200] + '...'

articles/forms.py
from email.policy import default
from django import forms
from matplotlib.image import thumbnail
from . import models
from ckeditor.widgets import CKEditorWidget


class CreateArticleForm(forms.ModelForm):
    body = forms.CharField(widget = CKEditorWidget())
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug','thumbnail']

class EditArticleForm(forms.ModelForm):
    def __init__(self, title, body, thumbnail,*args, **kwargs):
        super(EditArticleForm, self).__init__(*args, **kwargs)
        self.fields['title'].initial = title
        self.fields['body'].initial = body
    
    body = forms.CharField(widget = CKEditorWidget())
    class Meta:
        model = models.Article
        fields = ['title', 'body']
    
class SubmittedArticleForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body']
        widgets = {
            'body': CKEditorWidget(),
        }

    # def clean_slug(self):
    #     new_slug = self.cleaned_data['slug'].lower()

    #     if new_slug == 'create':
    #         raise forms.ValidationError('Slug may not be "create"')
    #     if models.Article.objects.filter(slug__iexact=new_slug).count():
    #         raise forms.ValidationError('Slug must be unique. We have "{}" slug already'.format(new_slug))
    #     return new_slug

accounts/views.py
from turtle import home
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from captcha.fields import CaptchaField
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from numpy import require

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    captcha = CaptchaField()

@csrf_exempt
def ajax(request):
    if request.method == 'POST':
        username = request.POST['username']
        if User.objects.filter(username=username).exists():
            return JsonResponse({'exists': True})
        else:
            return JsonResponse({'exists': False})

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    # this code will exectute if the request method is not POST or if the form is invalid
    return render(request, 'accounts/register.html', {'form': form})

def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

@login_required()
def logoutView(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')
    return render(request, 'home.html')

articles/views.py
from django.shortcuts import redirect, render
from articles.forms import CreateArticleForm, EditArticleForm, SubmittedArticleForm
from articles.models import Article
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html',context)

@login_required()
def create(request):
    if request.method == 'POST':
        form = CreateArticleForm(request.POST, request.FILES)
        if form.is_valid():
            # returns a new instance of the article (model of the form) 
            # but does not commit the save to the database yet
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('articles:get', article_slug=article.slug)
    else:
        form = CreateArticleForm()
    return render(request, 'articles/create.html', {'form': form})

@login_required()
def edit(request, article_slug):
    if request.method == 'POST':
        article = Article.objects.get(slug=article_slug)
        form = SubmittedArticleForm(request.POST)
        if form.is_valid():
            # returns a new instance of the article (model of the form) 
            # but does not commit the save to the database yet
            article.title = form.cleaned_data['title']
            article.body = form.cleaned_data['body']    
            article.save()
            return redirect('articles:get', article_slug=article.slug)
    if request.method == 'GET':
        article = Article.objects.get(slug=article_slug)
        form = EditArticleForm(article.title, article.body, article.thumbnail)
        return render(request, 'articles/edit.html', {'form': form, 'article': article})

@login_required()
def delete(request, article_slug):
    article = Article.objects.get(slug=article_slug)
    article.delete()
    return redirect('articles:index')

def get(request, article_slug):
    article = Article.objects.get(slug=article_slug)
    context = {
        'article': article
    }
    return render(request, 'articles/get.html',context)

bloggy/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

templates/about.html
{% extends 'base_layout.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About us</title>
</head>
<body>
    {% block content %}
    <!-- about us page centerd in the middle -->
    <div class="container p-5">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h1 class="display-4">About us</h1>
                    <p class="lead">we aim to teach everyone </p>
                    <hr class="my-4">
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi, dicta nam et unde, atque repellendus esse vero ex iure quos consequatur quidem. Aliquid tempora reiciendis expedita accusamus illo magnam nihil!</p>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quis facilis incidunt libero at facere nulla qui dolore quos quae nemo vel, fuga delectus sit deleniti aliquam. Mollitia, porro tempora?</p>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

templates/accounts/login.html
{% extends 'base_layout.html' %}

{% load static %}
{% load widget_tweaks %}


{% block content %}

<div class="p-3 mt-5 bg-opacity-10 border border-secondary border-start-1 rounded site-form">
    <h1 class="font-weight-bold text-center mt-3">Login</h1>
    <form method="POST" action="{% url 'accounts:login' %}">
        {% csrf_token %}

        {% include 'form.html' with form=form %}

        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <!-- submit button -->
        <div style="margin:auto; width: 60px;">
            <input class="btn btn-success" type="submit" value="Login">
        </div>
    </form>
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'base_layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<div class="p-3 mt-5 mb-5 bg-opacity-10 border border-secondary border-start-1 rounded site-form">
    <h1 class="font-weight-bold text-center mt-3">Sign Up</h1>
    <form method="POST" action="/accounts/register/" id="signup">
        {% csrf_token %}
        
        {% include 'form.html' with form=form %}

        <div style="margin:auto; width: 60px;">
            <input class="btn btn-success" type="submit" value="register">
        </div>
    </form>
</div>

<!-- <script src="{% static 'ajax.js' %}"></script> -->


{% endblock %}

templates/articles/create.html
{% extends 'base_layout.html' %}

{% load widget_tweaks %}
{% load static %}

    
{% block content %}
<div class="p-3 mt-5 mb-5 bg-opacity-10 border border-secondary border-start-1 rounded site-form">
    <!-- form to create new articles-->
    <h1 class="font-weight-bold text-center mt-3">Create Article</h1>
    <form method="POST" action="{% url 'articles:create' %}" enctype="multipart/form-data" class="w-100 center" onload="changeWidth()">
        {% csrf_token %}
        {{form.media}}
        {% include 'form.html' with form=form %} 
        <div style="width: 25%; margin:auto;">
            <input type="submit" value="Create Article" class="btn btn-success">
        </div>
    </form>
</div>
<script src="{% static 'load.js' %}"></script>
{% endblock %}

templates/articles/edit.html
{% extends 'base_layout.html' %}

{% load widget_tweaks %}
{% load static %}

    
{% block content %}
<div class="p-3 mt-5 mb-5 bg-opacity-10 border border-secondary border-start-1 rounded w-sm-50 site-form">
    <!-- form to create new articles-->
    <h1 class="font-weight-bold text-center mt-3">Edit Article</h1>
    <form method="POST" action="/articles/{{ article.slug }}/edit/" enctype="multipart/form-data" class="w-100 center" onload="changeWidth()">
        {% csrf_token %}
        {{form.media}}
        {% include 'form.html' with form=form %}
        <div style="width: 25%; margin:auto;">
            <input type="submit" value="Edit Article" class="btn btn-success">
        </div>
    </form>
</div>
<script src="{% static 'load.js' %}"></script>
{% endblock %}

templates/articles/get.html
{% extends 'base_layout.html' %}

{% block content %}
<!-- article details page -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-2 p-2 bg-secondary">{{ article.title }}</h1>
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ article.thumbnail.url }}" alt="{{ article.title }}" class="img-fluid">
                    <p class="mt-1">
                        <strong>Published by:</strong> {{ article.author }}
                    </p>
                </div>
                <div class="col-md-8">
                    <p>{{ article.body | safe }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            {% if article.author == request.user or request.user.is_superuser%}
                            <a href="/articles/{{ article.slug }}/delete" class="btn btn-sm btn-outline-danger">delete</a>
                            <a href="/articles/{{ article.slug }}/edit/" class="btn btn-sm btn-outline-secondary">Edit</a>
                            {% endif %}
                        </div>
                        <small class="text-muted">{{ article.created_at }}</small>
                    </div>
                </div>
                <div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}

templates/articles/index.html
{% extends 'base_layout.html' %}

{% block content %}

<!-- list of articles -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-2 p-2 bg-secondary">Articles</h1>
            <div class="row">
                {% for article in articles %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="card-img-top" src="{{ article.thumbnail.url }}" alt="Card image cap">
                        <div class="card-body"> 
                            <p class="card-text">{{ article.title }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="/articles/{{ article.slug }}/" class="btn btn-sm btn-outline-secondary">View</a>
                                    {% if article.author == request.user or request.user.is_superuser%}
                                    <a href="/articles/{{ article.slug }}/edit/" class="btn btn-sm btn-outline-secondary">Edit</a>
                                    {% endif %}
                                </div>
                                <small class="text-muted">{{ article.created_at }}</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

<!------------------------------------------------------>

{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
        <title>Articles</title>
    </head>
    <body>
        <!-- navigation bar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Bloggy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li {% if request.resolver_match.url_name == 'home' %} class="nav-item active" {% endif %}>
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li {% if request.resolver_match.url_name == 'index' %} class="nav-item active" {% endif %}>
                        <a class="nav-link" href="/articles/">Articles</a>
                    </li>
                    <li {% if request.resolver_match.url_name == 'about' %} class="nav-item active" {% endif %}>
                        <a class="nav-link" href="/about/">About</a>
                    </li>
                </ul>
                <form class="form-inline mr-5 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                
                {% if user.is_authenticated %}
                <a href="{% url 'articles:create' %}" class="btn btn-outline-success m-1 float-end">New Article</a>
                <div class="wrapper">
                    <form action="{% url 'accounts:logout' %}" class="" method="post">
                        {% csrf_token %}
                        <button class="btn btn-success btn-md active ml-1" type="submit" >Logout</button>
                    </form>
                </div>
                {% else %}
                <a href="{% url 'accounts:login' %}" class="ml-1"><button class="btn btn-success btn-md active" >Login</button></a>
                <a href="/accounts/register" class=""><button class="btn btn-secondary btn-md ml-2 active" >register</button></a>
                {% endif %}
                <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                    <a class="btn-floating btn-lg red">
                      <i class="fas fa-pencil-alt"></i>
                    </a>
                   
                    <ul class="list-unstyled">
                      <li><a class="btn-floating red"><i class="fas fa-star"></i></a></li>
                      <li><a class="btn-floating yellow darken-1"><i class="fas fa-user"></i></a></li>
                      <li><a class="btn-floating green"><i class="fas fa-envelope"></i></a></li>
                      <li><a class="btn-floating blue"><i class="fas fa-shopping-cart"></i></a></li>
                    </ul>
                </div>

            </div>
        </nav>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/filter.html
{% load static %}

<!-- filter bar for searching in articles -->

templates/form.html
{% load widget_tweaks %}

<!-- non field errors -->
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
{% for error in form.non_field_errors %}
    {{ error }}
{% endfor %}
</div>
{% endif %}

<!-- hidden fields -->
{% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
{% endfor %}

<!-- main fields-->

{% for field in form.visible_fields %}
<div class="form-group">
    {{ form.media }}
    {{ field.label_tag }}

    {% if form.is_bound %}
        {% if field.errors %}
            {% render_field field class="form-control is-invalid w-100" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                {{ error }}
                </div>
            {% endfor %}
        {% else %}
            {% render_field field class="form-control w-100" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control w-100" %}
    {% endif %}

    {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>
{% endfor %}

templates/home.html
{% extends 'base_layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    {% block content %}
    <!--- main content of the page centerd horizontaly and vertically -->
    <div class="container p-5">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h1 class="display-4">Welcome to Bloggy</h1>
                    <p class="lead">wanna know more in today's techs, jump in</p>
                    <hr class="my-4">
                    <p>our goal is to provide you with many useful articles in the tech fields that will make you up to date with the present trends.</p>
                    <a class="btn btn-success btn-lg" href="/articles/" role="button">Check our Articles</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    
</body>
</html>